# Part 1: Theoretical Questions

1.  Tensors: Tensors are multi-dimensional arrays used to represent data in TensorFlow. They can be scalars (0-D tensors), vectors (1-D tensors), matrices (2-D tensors), or higher-dimensional arrays. Tensors are the fundamental building blocks for representing data and performing mathematical operations in TensorFlow.

Variables: Variables are tensors that hold mutable state and are typically used to represent model parameters that need to be optimized during training. Variables are initialized with an initial value and can be updated using operations like assignment.

Datasets: Datasets are a data structure used for building efficient input pipelines in TensorFlow. They represent sequences of elements (such as tensors or NumPy arrays) and support various transformations and operations for preprocessing and batching data. Datasets are commonly used for loading and processing large datasets during training.

Sparse Tensors: Sparse tensors are a specialized data structure used for representing tensors with a large number of elements that are mostly zero. Sparse tensors store only the non-zero values along with their indices, allowing for significant memory savings and computational efficiency when working with sparse data.

These data structures form the foundation of TensorFlow and are essential for building and training machine learning models efficiently. They provide the necessary tools for representing and manipulating data, model parameters, and input pipelines throughout the machine learning workflow.

2.  TensorFlow Constant:

A TensorFlow constant represents a tensor whose value remains fixed throughout the execution of a TensorFlow graph.
Once defined, the value of a constant cannot be changed.
Constants are typically used to represent fixed values such as hyperparameters, input data, or model parameters that do not change during the execution of the graph.
Constants are immutable and cannot be modified during computation.
TensorFlow Variable:

A TensorFlow variable represents a tensor whose value can be changed during the execution of a TensorFlow graph.
Variables are mutable and can be modified using operations like assignment (assign()).
Variables are often used to represent trainable parameters of a model, such as weights and biases, which need to be updated during training to minimize the loss function.
Variables are mutable and can be modified during computation, making them suitable for storing and updating parameters during training.
In summary, TensorFlow constants are immutable tensors with fixed values, while TensorFlow variables are mutable tensors whose values can be modified during computation, typically used to represent model parameters that need to be updated during training.

3.   Matrix Addition:

Matrix addition involves adding corresponding elements of two matrices to produce a new matrix of the same shape.
In TensorFlow, matrix addition can be performed using the tf.add() function or the + operator.
Both methods allow for element-wise addition of two matrices of the same shape.
The resulting matrix will have the same dimensions as the input matrices, with each element being the sum of the corresponding elements from the input matrices.
Matrix Multiplication:

Matrix multiplication involves multiplying corresponding elements of rows and columns between two matrices to produce a new matrix.
In TensorFlow, matrix multiplication can be performed using the tf.matmul() function or the @ operator.
Both methods allow for matrix multiplication between two matrices, with the number of columns in the first matrix being equal to the number of rows in the second matrix.
The resulting matrix will have dimensions equal to the number of rows of the first matrix and the number of columns of the second matrix.
Element-wise Operations:

Element-wise operations involve applying arithmetic operations (such as addition, subtraction, multiplication, and division) to corresponding elements of tensors.
In TensorFlow, element-wise operations can be performed using functions like tf.add(), tf.subtract(), tf.multiply(), and tf.divide().
These operations are applied element-wise between corresponding elements of two tensors, producing a new tensor of the same shape.
Element-wise operations are useful for performing operations on tensors where each element's value is independently calculated based on the corresponding elements of other tensors.
In summary, TensorFlow provides functions and operators for performing matrix addition, multiplication, and element-wise operations efficiently. These operations are fundamental in many machine learning and numerical computing tasks and are essential for building and training deep learning models.

# Part 2: Practical Implementation

# Task 1: Creating and Manipulating Matrices

In [2]:
import tensorflow as tf

# Create a 2x2 matrix A with random values sampled from a normal distribution
A = tf.random.normal(shape=(2, 2))

# Display the values of matrix A
print("Matrix A:")
print(A)



Matrix A:
tf.Tensor(
[[ 1.0738744  -0.55689853]
 [-1.6660237  -0.2845878 ]], shape=(2, 2), dtype=float32)


In [4]:
import tensorflow as tf

# Define the dimensions of the matrix
x = 4

# Create the Gaussian matrix B using tf.random.truncated_normal
B = tf.random.truncated_normal(shape=(x, x), mean=0.0, stddev=1.0)

# Print the values of matrix B
print("Gaussian Matrix B:")
print(B.numpy())


Gaussian Matrix B:
[[-1.6381128  -0.20434417 -0.42558613  0.11995108]
 [ 1.3548584  -1.0029389   0.62856364  0.49502543]
 [ 0.76996154  0.75793165  0.6173063  -0.20136514]
 [-0.66030025 -0.11400644 -0.73703617 -0.69669586]]


In [5]:
import tensorflow as tf

# Define mean and standard deviation
mean = 2
stddev = 0.1  # Replace 0.x with the desired standard deviation

# Create a 2x2 matrix C with random values sampled from a normal distribution
C = tf.random.normal(shape=(2, 2), mean=mean, stddev=stddev)

# Display the values of matrix C
print("Matrix C:")
print(C)


Matrix C:
tf.Tensor(
[[2.0127728 2.0952168]
 [2.1207714 2.0340025]], shape=(2, 2), dtype=float32)


In [6]:
import tensorflow as tf

# Define matrix A and matrix B
A = tf.constant([[1, 2], [3, 4]])
B = tf.constant([[5, 6], [7, 8]])

# Perform matrix addition
D = tf.add(A, B)

# Print the result
print("Matrix D (Result of Addition):")
print(D.numpy())


Matrix D (Result of Addition):
[[ 6  8]
 [10 12]]


In [7]:
import tensorflow as tf

# Assume matrix C is already defined as shown previously
# For demonstration, redefining matrix C with fixed mean and stddev
mean_C = 2
stddev_C = 0.1
C = tf.random.normal(shape=(2, 2), mean=mean_C, stddev=stddev_C)

# Define matrix D, here we use random values with a different mean and stddev for variety
mean_D = 0
stddev_D = 1
D = tf.random.normal(shape=(2, 2), mean=mean_D, stddev=stddev_D)

# Perform matrix multiplication between C and D to get E
E = tf.matmul(C, D)

# Display the values of matrix E
print("Matrix E (Result of C * D):")
print(E)


Matrix E (Result of C * D):
tf.Tensor(
[[ 0.06812222 -4.4145107 ]
 [ 0.04806717 -4.293281  ]], shape=(2, 2), dtype=float32)


# Task 2: Performing Additional Matrix Operations

In [8]:
import tensorflow as tf

# Define the dimensions of the matrix
rows = 2
cols = 2

# Create the matrix F with random values
F = tf.random.uniform(shape=(rows, cols), minval=0, maxval=1)

# Print the matrix F
print("Matrix F (Random Uniform):")
print(F.numpy())


Matrix F (Random Uniform):
[[0.6294819  0.12578583]
 [0.47766197 0.7236941 ]]


In [9]:
import tensorflow as tf

# Assume matrix F is already defined or generated
# For demonstration, let's create a sample matrix F
F = tf.constant([[1, 2], [3, 4]])

# Calculate the transpose of matrix F and store the result in matrix G
G = tf.transpose(F)

# Display the values of matrix G
print("Matrix G (Transpose of F):")
print(G)


Matrix G (Transpose of F):
tf.Tensor(
[[1 3]
 [2 4]], shape=(2, 2), dtype=int32)


In [10]:
import tensorflow as tf

# Assume matrix F is already defined or generated
# For demonstration, let's create a sample matrix F
F = tf.constant([[1, 2], [3, 4]], dtype=tf.float32)  # Define matrix F

# Calculate the element-wise exponential of matrix F and store the result in matrix H
H = tf.exp(F)

# Display the values of matrix H
print("Matrix H (Element-wise exponential of F):")
print(H)


Matrix H (Element-wise exponential of F):
tf.Tensor(
[[ 2.7182817  7.389056 ]
 [20.085537  54.59815  ]], shape=(2, 2), dtype=float32)


In [11]:
import tensorflow as tf

# Assuming F and G are already defined
F = tf.constant([[1, 2], [3, 4]])
G = tf.constant([[5, 6], [7, 8]])

# Concatenate matrices F and G horizontally
I = tf.concat([F, G], axis=1)

# Print the concatenated matrix I
print("Matrix I (Concatenated Horizontally):")
print(I.numpy())


Matrix I (Concatenated Horizontally):
[[1 2 5 6]
 [3 4 7 8]]


In [12]:
import tensorflow as tf

# Assume matrix F and matrix H are already defined or generated
# For demonstration, let's create sample matrices F and H
F = tf.constant([[1, 2], [3, 4]], dtype=tf.float32)
H = tf.exp(F)  # Element-wise exponential of matrix F

# Concatenate matrix F and matrix H vertically to create matrix J
J = tf.concat([F, H], axis=0)

# Display the values of matrix J
print("Matrix J (Concatenation of F and H vertically):")
print(J)


Matrix J (Concatenation of F and H vertically):
tf.Tensor(
[[ 1.         2.       ]
 [ 3.         4.       ]
 [ 2.7182817  7.389056 ]
 [20.085537  54.59815  ]], shape=(4, 2), dtype=float32)
